name: Python application

on:
  workflow_call:
    inputs:
      tag:
        description: 'The tag to use for the release'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build executable
      run: |
        pyinstaller --onefile sinkholes.py
    - name: Get version
      id: version
      run: |
        echo "version=$(python -c "from __version__ import __version__; print(__version__)")" >> $GITHUB_OUTPUT
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sinkholes-linux
        path: |
          dist/sinkholes
          __version__.py

  build-windows:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
    - name: Build executable
      run: |
        pyinstaller --onefile sinkholes.py
    - name: Get version
      id: version
      run: |
        echo "version=$(python -c "from __version__ import __version__; print(__version__)")" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sinkholes-windows
        path: |
          dist/sinkholes.exe
          __version__.py

  build-mac:
    runs-on: macos-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build executable
      run: |
        pyinstaller --onefile sinkholes.py
    - name: Get version
      id: version
      run: |
        echo "version=$(python -c "from __version__ import __version__; print(__version__)")" >> $GITHUB_OUTPUT
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sinkholes-mac
        path: |
          dist/sinkholes
          __version__.py

  release:
    needs: [build-linux, build-windows, build-mac]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/sinkholes-linux/sinkholes
            artifacts/sinkholes-windows/sinkholes.exe
            artifacts/sinkholes-mac/sinkholes
          tag_name: ${{ inputs.tag }}
          name: Release ${{ needs.build-linux.outputs.version }}
          body: "New release of sinkholes"

